### ISSUE TITLE
Relative WorkspaceDirectory is computed from Visual Studio directory instead of solution directory

### ISSUE THREAD

**Issue by BlinD-HuNTeR** [ReMinoer/SubSolution#2]
I tried to set WorkspaceDirectory to parent directory (`..`), and the resulting path was actually the directory where Visual Studio is installed.

This happens because `SolutionBuilderContext::ComputeWorkspaceDirectoryPath` uses `Environment.CurrentDirectory` to compute relative paths. It should instead use the directory where the .subsln file is located.

**Comment by ReMinoer** [comment]
Thanks for the feedback. :)

Here is how I see things: `Environment.CurrentDirectory` shouldn't actually be used directly in the libraries. I will replace it with a `RootDirectory` parameter/property. And use `Environment.CurrentDirectory` value only for the command line executable.

Also you are right that the new `RootDirectory` should be set on the .subsln folder when the `SolutionBuilderContext` is created from `SolutionBuilderContext .FromConfigurationFileAsync`.

**Comment by ReMinoer** [comment]
Fixed with commit bde5b3c and released in version [0.4.1](https://github.com/ReMinoer/SubSolution/releases/tag/0.4.1).
