### ISSUE TITLE
Resolving $(SolutionDir) when including other solution files

### ISSUE THREAD

**Issue by icnocop** [ReMinoer/SubSolution#4]
Hi.

Thank you for SubSolution.

I'm wondering if there's a way to dynamically resolve the MSBuild `$(SolutionDir)` macro/property correctly, relative to the new/generated solution file and the original one that was included?

I've attached an example set of files that illustrates the issue I'm experiencing.

[SubSolutionTest.zip](https://github.com/ReMinoer/SubSolution/files/8792804/SubSolutionTest.zip)

Steps to reproduce:

1. Download and extract SubSolutionTest.zip to a folder called SubSolutionTest
2. Open `Solution1\ClassLibrary1\ClassLibrary1.csproj` in notepad and notice the line at the end of the file: `<Import Project="$(SolutionDir)MyPropertyFiles\MyPropertyFile.props" />`.
3. Open `Solution1\Solution1.sln` in Visual Studio and notice `ClassLibrary1` can be loaded correctly.
4. run `cd SubSolutionTest`
5. run `subsln generate Test.subsln --import-fallback --force`
6. Open the generated `Test.sln` in Visual Studio and notice `ClassLibrary1` cannot be loaded and Visual Studio displays the following error:
```
The imported project ".\SubSolutionTest\MyPropertyFiles\MyPropertyFile.props" was not found. Confirm that the expression in the Import declaration ".\SubSolutionTest\MyPropertyFiles\MyPropertyFile.props" is correct, and that the file exists on disk.  .\SubSolutionTest\Solution1\ClassLibrary1\ClassLibrary1.csproj
```

Is it possible for `ClassLibrary1` to be loaded correctly by both solution files without modification to the original solution or project files?

For example, could a `Directory.Build.props` file resolve this issue?

Thank you.

subsln 0.5.2+5debbb70b73093b9bd6ae2c0684ff2751e29980a
SubSolution (2022) 0.5.2
Visual Studio 2022 17.2.2

**Comment by ReMinoer** [comment]
Hi Rami. 😃 
Thank you for your feedback.

**It would be indeed interesting for SubSolution to define some MSBuild variables such as `$(SolutionDir)` to read the projects using them. I will look into it and see what is possible.**

That said, using $(SolutionDir) in a project file only make sense if you plan to change the targeted .props file depending of the running solution.
**If your project should always import the same .props file, you should prefer the relative path "..\MyPropertyFiles\MyPropertyFile.props" in your `<Import>`. I tested and it seems to work.**

And you can still take a look at Directory.Build.props files. It's a very simple way to share configuration through many projects. 👍

**Comment by icnocop** [comment]
I was able to resolve this issue after replacing $(SolutionDir) with relative paths.

I'm closing this issue because it's not specific to SubSolution.

Thank you.
