### ISSUE TITLE
No projects are found when WorkspaceDirectory is different than solution directory.

### ISSUE THREAD

**Issue by BlinD-HuNTeR** [ReMinoer/SubSolution#5]
At [SolutionBuilder.cs, Line 269](https://github.com/ReMinoer/SubSolution/blob/29f1311552df73e2b5c8efff395fae10e7853263/Sources/SubSolution.Builders/SolutionBuilder.cs#L269), it takes the resolved paths from `GetMatchingProjectPaths` (which are relative paths), and tries to make absolute paths using `_solution.OutputDirectoryPath` as the root. It should use `_workspaceDirectoryPath` instead.

Because of that, the patterns are resolved correctly, but the reading task doesn't find the files, unless both directories are the same, which defeats the whole purpose of WorkspaceDirectory.

**Comment by ReMinoer** [comment]
Missed that. Thank you for the investigation ! 😃
Fixed with e45f3de and released as 0.5.3.
